apiVersion: v1
kind: Service
metadata: 
  name: platformnpservice-srv
spec:
  type: NodePort
  selector:
    app: microsierviceswebapi
  ports:
    - name: microsierviceswebapi
      protocol: TCP
      port: 80
      targetPort: 80